samber/lo

- intersect.go
- slice.go
Hello
Isn't it better to use `struct{}` for sets values? Bools use 1 byte of memory but `struct{}`s do not use memory at all!
> Use struct{} for sets

- map_test.go
- parallel/slice.go
The slice is pre-allocated, a mutex is not needed.
> parallel: remove mutex from Map and Times

- slice.go
After doing a little bit of testing it's clear that `append` do some additional processing. I got around 25-30% speed improvements with these modifications.
> Improve `Map[T any, R any]` speed

- README.md
Looks like a simple typo -- there is an extra argument to the `lop.Match()` example.
> readme has extra arg for lop.Map() example

- util_test.go
* Add a new test case to reach 100% coverage in `RangeWithSteps`.
* Reverse the order of the [is.Equal](https://pkg.go.dev/github.com/stretchr/testify/assert#Equal) parameters (`expected` should be the first parameter)
> [func Equal(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool](https://pkg.go.dev/github.com/stretchr/testify/assert#Equal)
> test(util): add test case and fix assert logic in RangeWithSteps

- Dockerfile
Since you made a **WORKDIR** command before a **COPY** with the same destination path. you just need a short declaration.
> [fix] Dockerfile path in COPY

- README.md
- find.go
- find_test.go
FindIndex searches an element in a slice based on a predicate and returns the index and true.
It returns -1 and false if the element is not found.
#61
> Implement FindIndex

- README.md
I added description of `Empty()` usage sample in readme.
Closes #69
> doc: add description of Empty() to readme

- condition.go
- condition_test.go
this PR is inspired by the issue #65 
we want If/ElseIf/Else ’s result parameter could be a function, so i add IfF/ElseIfF/ElseF functions and make this PR.
> feat: add IfF、ElseIfF、ElseF

- README.md
the output in readme is wrong:
```go
func main() {
r1 := lo.Clamp(0, -10, 10)
// 10
r2 := lo.Clamp(-42, -10, 10)
// -42
r3 := lo.Clamp(42, -10, 10)
// 42
fmt.Println(r1, r2, r3)
}
```
Actual: `0 -10 10`
> fix: wrong examples of Clamp function in readme

- README.md
Switch Mixed:
```go
result := lo.Switch[int, string](1).
CaseF(1, func() string {
return "1"
}).
Default("42")
// "42"  <- should be "1"
```
> fix: wrong output of a Switch example in readme

- README.md
Prepended `lo.` to make it consistent with other examples
> [docs] Use package name in Coalesce example

- README.md
- slice.go
- slice_test.go
Small helper function which returns slice with all elements mapped to any type.
It is common for other libraries to accept a variadic number of arguments of interface type. _ToAnySlice_ allows easily to convert slice with concrete type to any
> feat: Add ToAnySlice

- type_manipulation.go
- type_manipulation_test.go
Hey,
wanted to add a basic function that returns the value of a pointer.
When the pointer is `nil` it returns the default value of the type. I.e. for a `nil` string pointer, it would return an empty string `""`.
> feat: add `FromPtr` function

- README.md
- slice.go
- slice_test.go
`Compact` returns a new slice with all zero values removed (`0` for `int`, `false` for `bool`, `""` for `string` and so on). This is inspired by [Lodash `compact` method](https://lodash.com/docs/4.17.15#compact).
> feat: adding Compact

- find.go
- find_test.go
- Fixed incorrect Nth behavior for -1 index.
- More performant index checking (haven't tested, but removed Math.Abs call and casting to/from float64)
~~Used constraints.Integer for 'nth' parameter.~~
~~Panic instead of raising error on out of range.~~
> Nth: addressing #136 - fixing -1 bug on slice of length 1. 

- find.go
Mentioned in my original issue #136 and is superset to PR #137 
~~**Panic**~~
~~[Three months ago, Nth was changed to return an error instead of panicking.](https://github.com/samber/lo/commit/a59137782c3457b6039f8654b1cc9fa5af48e948) Admittedly, the explicit error handling is arguably more Go-y, however, I propose going back to panicking because:~~
~~- it's a simpler method signature, no error handling~~
~~- it is a similar behavior to normal slice accessing: `mySlice[outOfBoundsIndex]` panics~~
**constraints.Integer**
This is a more generic, backwards-compatible method signature change. Any integer type will work for `nth` parameter.
> Nth: use constraints.Integer for nth param.

- README.md
- slice.go
- slice_test.go
Associate returns a map containing key-value pairs provided by transform function applied to elements of the given slice.
If any of two pairs would have the same key the last one gets added to the map.
The returned map preserves the entry iteration order of the original array.
> feat: Add Associate function

- map.go
- map_test.go
Add a method to transform map[x]y to slice according to given func.
somthing like :
result1 := MapToSlice(map[int]int{1: 1, 2: 2, 3: 3, 4: 4}, func(x int, v int) string {
return fmt.Sprintf("%d_%d", x, v)
})
> feat: add MapToSlice method

- slice.go
- slice_benchmark_test.go
Hello! 👋
I've made some optimizations for slices. There are also benchmarks to check the results.
And my results under:
```
go version go1.19 darwin/arm64
macbook air m1
goos: darwin
goarch: arm64
```
**Flatten**
```
name                    old time/op    new time/op    delta
Flatten/ints_10-8          294ns ± 1%     116ns ± 2%  -60.65%  (p=0.000 n=9+10)
Flatten/ints_100-8        23.7µs ± 0%     5.8µs ± 0%  -75.58%  (p=0.000 n=10+8)
Flatten/ints_1000-8       2.47ms ± 2%    0.63ms ± 1%  -74.58%  (p=0.000 n=10+8)
Flatten/strings_10-8       705ns ± 1%     227ns ± 0%  -67.83%  (p=0.000 n=10+9)
Flatten/strings_100-8     77.5µs ±15%    25.2µs ± 5%  -67.42%  (p=0.000 n=10+10)
Flatten/strings_1000-8    24.2ms ± 1%     5.5ms ± 2%  -77.46%  (p=0.000 n=10+10)
name                    old alloc/op …
```
> Fix: up to 80% speed and memory optimizations for slices

- slice.go
change `func Slice[T comparable]` to `func Slice[T any]` beacuse `comparable` is not actually required here.
This should not be a breaking change because any `any` contains `comparable`.
close #206
> `Slice` can take any slice

- channel_test.go
- condition_test.go
- find_test.go
- func_test.go
- intersect_test.go
- map_test.go
- math_test.go
- retry_test.go
- slice_test.go
- string_test.go
- tuples_test.go
- type_manipulation_test.go
> Parallel tests everywhere

- README.md
- condition.go
- condition_test.go
A continuation of issue https://github.com/samber/lo/issues/65 (and by extension PR https://github.com/samber/lo/pull/89)
> feat: add TernaryF function

- README.md
- errors.go
- errors_test.go
> Add function Validate that creates an error when a condition is not met

- CHANGELOG.md
- README.md
- channel.go
- channel_test.go
- ToChannel
- Batch
- BatchWithTimeout
- Generator
Discussed here: #94
> New helper collection: channel

- README.md
- map.go
- map_test.go
Add a method to transform map[k]v  to a new map[s]r  according to a given transformer to all entries.
> feat: Add MapEntries function

- README.md
- slice.go
- slice_test.go
`Interleave` interleaves input slices into single output result
> add Interleave helper to slices

- channel.go
- channel_test.go
add two func ChannelCollector and BufferedChannelCollector for channel helper,
collect messages from multiple input channels into one channel.
> feat: add ChannelMerge

- intersect.go
- intersect_test.go
Hi @samber 
I have made some improvement of func Union.
1. func can accept more than 2 params
2. use less memory and less iteration
> feat: improve Union

- channel.go
- channel_test.go
- errors_test.go
- map_test.go
- parallel/slice_test.go
- slice_test.go
I noticed that some functions and function aliases weren't being completely covered by the tests, so I decided to create and improve some tests.
I decided to separate by commits instead of PRs to not spam the repository.
I'm not sure if I chose the best approach in each test, so I'm willing to change and learn more :)
> chore: test coverage improvement

- channel_test.go
- find_test.go
- slice_example_test.go
- type_manipulation_test.go
Made the project to smell good
> fix: resolved code smells

- slice.go
- slice_test.go
Previous:
```go
lo.Slice(arr, -1, 10) // panic: runtime error: slice bounds out of range
```
After fixed:
```go
lo.Slice([]int{0, 1, 2, 3}, -10, -1) // []int{}
lo.Slice([]int{0, 1, 2, 3}, -100, 2) // []int{0, 1}
```
I think that compared to the native method(arr[1:10]), the meaning of lo.Slice() is to avoid panic caused by out-of-bounds as much as possible. So I fixed it.
> fix: panic when Slice() accepts a negative index

- README.md
- string.go
- string_test.go
> Add RandomString

- README.md
- retry.go
- retry_test.go
> feat: adding `AttemptWhile` and `AttemptWhileWithDelay`

- slice.go
This PR adds capacity hint in `Associate`, to make it more memory efficient
> fix: set map capacity in Associate

- .github/workflows/release.yml
Add a job into the CI for the package release.
I clean up the project before release, in order to remove any dev dependencies from the final package:
```sh
rm -rf *_test.go ./parallel/*_test.go docker-compose.yml img/
```
@seguins thanks for your help.
> CI: clean-up dependencies on release

- map.go
- map_test.go
Motivation : reducing boilerplate when setting sensible defaults when a key is not found in a map
```go
func ValueOr[K comparable, V any](in map[K]V, key K, fallback V) V 
```
<hr/>
```go
r1 := ValueOr(map[string]int{"foo": 1}, "bar", 2)
is.Equal(r1, 2)
```
> feat : adding ValueOr

- README.md
One interesting use case of `FlatMap` that isn't intuitively obvious from the docs is the ability to return `nil`. For example,
```golang
var key = map[string][]string{"a": ["b","c"], "d": ["e","f"]}
var myKeys = []string{"a","c","d","g"}
lo.FlatMap(key, func(s string, _ int) []string { return key[s] })
// returns []string{"b","c","e","f"}
```
The docs should explicitly mention what happens if you return `nil`, so a user would be able to deduce this use case themselves.
> Update FlatMap docs to talk about nil case

- channel.go
Fix formatting of deprecation notices in Go doc comments:
* add missing empty line before the `Deprecated:` prefix. See https://github.com/golang/go/wiki/Deprecated
* add [doc links](https://go.dev/doc/comment#doclinks) to allow tooling (ex: pkg.go.dev) to link to the replacement
> doc: fix formatting of deprecated notices

- README.md
- type_manipulation.go
- type_manipulation_test.go
> Add EmptyableToPtr

- slice_benchmark_test.go
- type_manipulation.go
Hi, I found a way to reduce the number of allocations and improve the overall performance of `ToSlicePtr`.
here is simple benchmark:
```
name           old time/op    new time/op    delta
ToSlicePtr-10    1.18ms ± 6%    0.25ms ± 5%   -78.60%  (p=0.000 n=14+12)
name           old alloc/op   new alloc/op   delta
ToSlicePtr-10    1.60MB ± 0%    0.80MB ± 0%   -49.92%  (p=0.000 n=15+15)
name           old allocs/op  new allocs/op  delta
ToSlicePtr-10      100k ± 0%        0k ± 0%  -100.00%  (p=0.000 n=15+15)
```
> ToSlicePtr: reduce allocations and improving speed

- .github/workflows/test.yml
* Added CI tests of Go 1.19, 1.20, 1.21, 1.22 and stable
* Codecov job runs on go 1.18 only
> CI: tests on multi go versions

- concurrency.go
- errors.go
- tuples.go
- types.go
Long lines are less long
One style with
https://github.com/samber/lo/blob/5777c5a3ee09f852d55a5bb5f585fcaeb5a0aedb/errors.go#L187
https://github.com/samber/lo/blob/5777c5a3ee09f852d55a5bb5f585fcaeb5a0aedb/func.go#L37
In the doc signature in the official vscode extension are also omitted
I would omit it here too, how does it do vscode, but it's not necessary
https://github.com/samber/lo/blob/5777c5a3ee09f852d55a5bb5f585fcaeb5a0aedb/slice.go#L25
> style: no extra any type parameter

- math.go
- math_example_test.go
- math_test.go
**Title:** Add Mean and MeanBy functions for ints and floats
**Issue:** https://github.com/samber/lo/issues/412
**Description:**
This PR adds two new functions to the math library:
- **Mean:** Calculates the mean of a collection of numbers.
- **MeanBy:** Calculates the mean of a collection of numbers using a provided iteratee function.
These functions are implemented using generics to support both integers and floats. They do not cater to complex types, as the concept of a mean for complex numbers can be misleading and requires specialized handling.
Thorough unit tests have been included to ensure the correctness of the functions.
**Code Changes:**
- Added two functions in _math.go_
- Added tests for the two functions in math_test.go
**Testing:**
All tests pass successfully.
**Reviewers, …
> Adding Mean and MeanBy

- README.md
Use lower case to make sure the link in pkg.go.dev is working.
> Fix IsNil link for pkg.go.dev

- README.md
The first parameter in [strconv.FormatInt](https://pkg.go.dev/strconv#FormatInt) accepts `int64`, so we need to use int64 in example.
> Docs: should use type int64 for lo.FlatMap in example

- README.md
- type_manipulation.go
- type_manipulation_test.go
add Nil function to return nil value of type
> feat(type_manipulation): add Nil

- README.md
- find.go
- find_test.go
adding two new functions to `find.go` for fetching the first element of the slice.
> Add First and FirstOrZeroValue functions

- README.md
different expression but same meaning. lo.Unpack2 has a comma but tuple2.Unpack() does not.
> inconsistent expression in README.md

- intersect.go
When I call this method recursively, slices and maps are frequently expanded, resulting in poor performance
> perf: Optimize the performance of union method, avoid repeated expansion

- README.md
- concurrency.go
- concurrency_test.go
```go
ok := WaitFor(func(i int) bool {
return i % 3 == 2
}, 10*time.Millisecond, time.Millisecond)
```
> Adding lo.WaitFor

- README.md
- slice.go
- slice_test.go
Inserts an element or multiple elements at index i.
> Add slice Splice an element or multiple elements at index i.

- README.md
- slice.go
- slice_test.go
Add a new method `Concat` similar to the one in lodash, it creates a concatenated slice which is independent of the original slice, unlike `append`. This comes in handy when you need to create multiple slices from one base slice
> Add new method Concat

- map.go
- map_test.go
Heuristically preallocate in `Assign`.
Assumption is that `Assign` is typically called with maps with different keys. For this invocations the benefit is the greatest.
Worst case scenario is when all the keys in all the merged maps are the same. The allocations for those calls are unnecessary but the execution time is roughly the same.
The preallocation factor can be decreased to e.g. half the count of all the entries in all the provided maps to try to cover both mentioned scenarios.
```
benchstat -confidence 0.6 old.txt new.txt | cb
goos: darwin
goarch: arm64
pkg: github.com/samber/lo
│   old.txt    │              new.txt               │
│    sec/op    │   sec/op     vs base               │
Assign/32768/different-10    3.659m ± 1%   2.365m ± 1%  -35.36% (p=0.002 n=6)
Assign/32768/same-10 …
```
> perf: preallocate in Assign

- README.md
- find.go
- find_test.go
This query adds two functions EarliestBy and LatestBy, which are helpful when dealing with slice of structures or more complex time calculation cases.
> feat: adding EarliestBy and LatestBy functions

- slice.go
- slice_test.go
raising a fix as mentioned in: https://github.com/samber/lo/issues/438
> fix: chunk memory leak, bug fix

- README.md
- concurrency.go
- concurrency_test.go
- lo_test.go
Discussed here
- https://github.com/samber/lo/pull/269#discussion_r1659280603
> feat: add WaitForWithContext

- README.md
1. The method lo.DropByIndex() was intended to be used, but lo.Drop() was used instead.
2. The output describe of lo.DropByIndex() is incorrect.
> Docs: Wrong method reference and output in readme

- README.md
Duration3 needs 4 assignments to call.
To match`TryOf` documentation,  `str, nbr, err, duration` names are used for the assignments.
ref: https://github.com/samber/lo/pull/471 ( released at https://github.com/samber/lo/releases/tag/v1.41.0 )
> Fix documentation for Duration3

- README.md
- map.go
- map_example_test.go
- map_test.go
Resolved Issue : https://github.com/samber/lo/issues/452
Added : 
- Accept Multiple maps as vaargs in Keys
- Accept Multiple maps as vaargs in Values
- Added UniqKeys which creates an array of unique map keys. 
- Added UniqValues which creates an array of unique map values. 
- Added Test for the same
> Keys+Values: accept multiple maps (vaargs) - Adding UniqKeys+UniqValues

- README.md
- slice.go
> Update  foreachwhile readme.md

- README.md
- type_manipulation.go
@samber SSIA. Thank you for nice package!
To update README and add playground for `FromSlicePtrOr`
> docs: fix example README, add playground (FromSlicePtrOr)

- parallel/slice.go
> fix: order of GroupBy and PartitionBy

- README.md
Fixed outdated (wrong parameter order) for FromSlicePtrOr.
> Fix outdated example go dev code for FromSlicePtrOr doc 

- README.md
- intersect.go
- type_manipulation.go
- type_manipulation_test.go
https://go.dev/ref/spec#The_zero_value does not define “empty value”. It informally mentions “empty value”, meaning (non-nil && 0-length) slice or map.
> Note that the zero value for a slice or map type is not the same as an initialized but empty value of the same type.
> docs: clarify `Empty` returns zero value

- README.md
- slice.go
- slice_example_test.go
- slice_test.go
> feat: add UniqMap

- README.md
- slice.go
- slice_test.go
Adding this per this comment: https://github.com/samber/lo/pull/566#issuecomment-2523502234
> feat: add CrossJoin function

- type_manipulation.go
- type_manipulation_test.go
Hello, this pr Implement CoalesceOrEmptySlice Function;
coalesce function for slices, ensure return not nil slice.
> feat: Implement CoalesceOrEmptySlice Function

- README.md
- channel.go
- channel_test.go
> feat: adding lo.BufferWithContext

- README.md
- slice.go
- slice_example_test.go
- slice_test.go
> feat: add SliceToSet

- README.md
- type_manipulation.go
- type_manipulation_test.go
As we already have `IsEmpty` & `IsNotEmpty`; it's reasonable to add `IsNotNil`.
> feat: Add IsNotNil

- slice.go
- slice_test.go
This PR introduces a new function ChunkMap, which splits a given map into chunks of a specified size. This functionality helps manage larger datasets by allowing developers to process them in smaller, more manageable pieces.
Changes Made:
Added the ChunkMap function to slice.go.
Implemented a simple chunking mechanism that creates an array of maps.
Added tests to validate the functionality, focusing on the number of chunks produced rather than the order or specific values of the elements.
Usage:
`result := ChunkMap(map[string]int{"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}, 2)`
This will return an array of maps, each containing up to 2 key-value pairs from the original map.
[Run it on Playground](https://go.dev/play/p/VOr0hA5RqsK)
Reference:
This PR addresses the request made in Issue #533, …
> feat: Implement ChunkMap Function (#533) 

- README.md
- retry.go
- retry_test.go
This PR adds lodash style 'throttle'.
NewThrottle function create a throttled instance that grants given functions are invoked only once in each interval.
It returns 2 functions, First one is throttled function and Second one is purge function which invokes given functions immediately and reset interval timer.
#396 
Thank you.
> Add NewThrottle

- README.md
- math.go
- math_test.go
Currently playing around with Go on Advent of Code and found that a Product or ProductBy function would be useful, and fit in well with the preexisting Sum and SumBy functions
Used as such:
```
list := []int{1, 2, 3, 4, 5}
product := lo.Product(list)
// 120
```
```
strings := []string{"foo", "bar"}
product := lo.ProductBy(strings, func(item string) int {
return len(item)
})
// 9
```
Hope its useful!
> feat: add `Product` and `ProductBy` functions

- slice.go
Implemented a new function to GroupBy.
This Implementation allows to map the values on the same iteration.
Sending an identity function as the `iterateeValue` will de facto result in a normal GroupBy operation.
> Implemented GroupByMap

- slice.go
- slice_test.go
- Modify the iteration function parameters in the `UniqueBy`, `GroupByMap`, and `Keyify` functions to use index access for collection elements. See: #428 #475 
- Optimize parameter naming in the `GroupByMap` function to improve code readability. See: #443 
- Add test cases for the `GroupByMap` function to cover different types of inputs. See: #443
> Perf(slice): Optimize iteration function parameters and add test cases

- README.md
- condition.go
Tiny addition suggested to warn about unexpected nil-pointer trap.
See https://github.com/samber/lo/issues/605
> fix: Issue 605 (README for Ternary()

- README.md
- find.go
- find_test.go
Closes: #602 
- `NthOr`: Returns the element at the specified index or a provided fallback value if the index is out of bounds.
- `NthOrEmpty`: Returns the element at the specified index or the zero value for the slice's element type if the index is out of bounds.
> feat: Add NthOr and NthOrEmpty functions

- slice.go
Filter / Map already preallocate the result slice, don't see why FilterMap shouldn't work the same way
> Preallocate result in FilterMap

- README.md
Fixed the error in the usage example of `lo.Latest` in readme.md
```go
use []time.Time{…} (value of type []time.Time) as time.Time value in argument to lo.Latest
```
> Fixed the error in the usage example of lo.Latest in readme.md

- Makefile
- slice.go
Prevents memory leak and free memory from initial collection.
> fix(chunk): Copy chunk in a new slice

- channel_test.go
- concurrency_test.go
- condition_test.go
- errors_test.go
- find_test.go
- intersect_test.go
- map_test.go
- math_test.go
- mutable/slice_test.go
- parallel/slice_test.go
- retry_test.go
- slice_test.go
- string_test.go
- tuples_test.go
- type_manipulation_test.go
Made some minor tweaks to the unit tests based on recommendations from the `testifylint` golangci-lint linter.
The most common issue was reversed `expected` and `actual` arguments, which can cause confusing failure messages.
> lint: Apply testifylint linter recommendations

- .github/workflows/lint.yml
- README.md
- channel.go
- condition.go
- errors.go
- find.go
- func.go
- img/README.md
- internal/rand/ordered_go118.go
- internal/rand/ordered_go122.go
- intersect.go
- map.go
- math.go
- mutable/slice.go
- mutable/slice_example_test.go
- parallel/slice.go
- retry.go
- slice.go
- slice_test.go
- string.go
- tuples.go
- type_manipulation.go
- types.go
Improved the documentation to use more standard English, discovered during my work on #672. In addition to grammar fixes, I've removed the "truthy" and "array" terminology since they're not relevant here.
> docs: grammar improvements

- .github/workflows/lint.yml
- channel_test.go
- find_test.go
- intersect_test.go
- map_test.go
- math_test.go
- mutable/slice_test.go
- parallel/slice_test.go
- retry_test.go
- slice_test.go
- string_test.go
- type_manipulation_test.go
Various unit test improvements that weren't caught by the recent introduction of the `testifylint` linter, discovered during my work on #672. Each commit addresses a different issue. These can be squash merged in their entirety or I can create more specific individual PRs if preferred.
> lint: unit test improvements

- .github/workflows/lint.yml
- intersect_example_test.go
- map_example_test.go
- slice_example_test.go
Fixed a couple of example issues, the most serious being the incorrectly named `ExampleReplaceAll` function which actually demonstrates the `Compact` function.
> fix: minor example issues

- .github/workflows/lint.yml
- intersect.go
- intersect_test.go
- slice.go
- slice_test.go
I noticed that unlike the other functions that receive and return `[]T`, `WithoutBy` and `DropByIndex` don't use the `Slice ~[]T` pattern to preserve aliased slice types.
> feat: preserve type alias in DropByIndex and WithoutBy

- .github/workflows/lint.yml
- errors.go
- intersect_test.go
- slice.go
- slice_test.go
- tuples_test.go
- type_manipulation.go
The latest golangci-lint version now warns against naked returns. This PR fixes those and also removes unnecessary named return parameters in a few places. IMO named parameters should only be used on functions that use `recover()` and functions that have > 2 non-obvious return values.
> lint: fix CI warnings and avoid named return parameters

- .golangci.yml
- README.md
- channel.go
- channel_test.go
- condition_test.go
- errors_example_test.go
- errors_test.go
- find.go
- find_test.go
- internal/rand/ordered_go118.go
- map_benchmark_test.go
- map_test.go
- math.go
- math_test.go
- parallel/slice_test.go
- retry.go
- retry_example_test.go
- retry_test.go
- slice_test.go
- string_test.go
- type_manipulation.go
- type_manipulation_test.go
Enable 7 more useful golangci-lint linters.
Fairly simple fixes, except perhaps the `thelper` one which removes the unnecessary `mapEntriesTest` function to simplify and improve readability of `TestMapEntries`.
> lint: enable 7 more linters

- slice.go
Chaining `TrimLeft` and `TrimRight` means the input collection will be unnecessarily "Keyified" twice.
Speaking of trim helpers, I was surprised to see that `TrimPrefix` trims all instances of the leading slice, not just the first. This is different from the stdlib `strings.TrimPrefix` and should probably be documented. Same with the suffix version.
> perf: avoid Keyify twice in Trim

- find.go
- map.go
Should we apply the #692 fix to map access everywhere? I can't find any compelling reasons not to.
> perf: optimize map access everywhere

- it/seq.go
- it/seq_test.go
- slice.go
* Implementation of conversion from slice to map without index passed to transformation function through the similar conversion but with index passed to transformation function (refer to https://github.com/samber/lo/pull/697/files#r2400392214).
* Implementation of conversion from iterator to map without index passed to transformation function through the similar conversion but with index passed to transformation function (refer to https://github.com/samber/lo/pull/672/files#r2400411494).
> feat: from slice/iterator to map with index passed
