Dockerfile, Makefile, README.md, go.mod, go.sum
```
$ go test -benchmem -bench ./...
go: downloading github.com/thoas/go-funk v0.9.1
goos: linux
goarch: amd64
pkg: github.com/samber/lo
cpu: Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
BenchmarkMap/lo.Map-8         	       8	 131041218 ns/op	39998055 B/op	 1000001 allocs/op
BenchmarkMap/lop.Map-8        	       2	 509805437 ns/op	120018304 B/op	 3000214 allocs/op
BenchmarkMap/reflect-8        	       2	 840512374 ns/op	170325888 B/op	 4000042 allocs/op
BenchmarkMap/for-8            	       9	 127074794 ns/op	39998040 B/op	 1000001 allocs/op
PASS
ok  	github.com/samber/lo	7.531s
```
=> Adding benchmarks

slice.go
=> fix(shuffle): use fisher-yates algo

map_test.go, slice.go
- use EqualValues for map tests
- update shuffle to default from rand which uses Fisher-Yates [1]
[1] https://en.wikipedia.org/wiki/Fisher–Yates_shuffle
=> update map test and Shuffle

map.go, map_test.go
* Add MapValues like kotlin  
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map-values.html
=> Add MapValues

slice.go, slice_test.go
* Add FlatMap    
ex: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap
=> Add FlatMap

README.md
I spent a little time cleaning up the grammar to make it read better.
I hope you don't mind.
=> readme: clean up some grammar

README.md, drop.go, drop_test.go
*) https://lodash.com/docs/4.17.15#drop
*) https://lodash.com/docs/4.17.15#dropRight
*) https://lodash.com/docs/4.17.15#dropWhile
*) https://lodash.com/docs/4.17.15#dropRightWhile
=> Add Drop, DropRight, DropWhile and DropRightWhile

README.md, map.go, map_test.go, slice.go, slice_test.go
Add support for lodash's keyBy utility
=> Add KeyBy 

README.md
try it in https://go.dev/play/p/Wrv0uR1HlbP?v=gotip
=> doc update: swap KeyBy parameters

tuples_test.go
=> Add test for zip

Dockerfile
=> Change go version to go1.18

README.md, slice.go, slice_test.go
=> Add Count/CountBy implementation

slice.go, slice_test.go
add FilterMap function, which performing filtering and mapping in a single call. 
this PR is inspired by the issue #84
=> feat: add FilterMap

map.go, pointers.go, slice.go, try_test.go
- fix typo in comment
- simplify code
- remove unreachable code in test
=> fix: simplify code and fix typo

README.md, util.go, util_test.go
closes https://github.com/samber/lo/issues/72
=> [Feature]: Implement Must

README.md, concurrency.go, concurrency_test.go
=> Implements Async

README.md, find.go, find_test.go, slice_test.go
Addresses issues #52, #54 and #59
=> Adding FindOrElse and tests

README.md, tuples.go, tuples_test.go
=> Add helper function to create tuple from a list of values

.gitignore, README.md, map.go, map_test.go
Closes https://github.com/samber/lo/issues/56
=> [Feature]: Added ValuesF helper

README.md, errors.go, errors_test.go
=> Fix Must to receives 'err any' 

README.md, tuples.go, tuples_test.go
=> Implement Unpack{2->9}

README.md, slice.go, slice_test.go
=> feat: add `Slice`

CHANGELOG.md, README.md, retry.go
Signed-off-by: Ryan Russell <git@ryanrussell.org>
=> chore(readability): Fix typos in docs and `retry.go`

README.md, errors.go, errors_test.go
=> Add context to Must panic message

README.md, func.go, func_test.go
=> Add Bind #126

README.md
1. Rearranged the links according to the documentation below
2. Fixed titles
3. Added anchor links to each doc for faster navigation
=> feat: Add anchor links in README docs

README.md, type_manipulation.go, type_manipulation_test.go
=> Add FromPtrOr

README.md
=> chore: Fix a typo

README.md, string.go, string_test.go
Follow the best implementation found on StackOverflow by Igor Mikushkin https://stackoverflow.com/questions/25686109/split-string-by-length-in-golang
closes #187
=> Implement ChunkString

find.go
=> feat: relax FindKeyBy constraint

README.md, slice.go, slice_example_test.go
For each helper:
- Godoc examples (xxx_example_test.go file)
- Go playground
- link in helper comment
- link in readme
=> Doc: adding examples

Makefile
fix issue https://github.com/samber/lo/issues/232
=> make it to go install for nancy

README.md
=> chore: Fix a typo(Range Section)

README.md, slice.go, slice_test.go
=> Add CountValues function

func.go, func_test.go
=> more variants of the Partial function, #235

README.md
=> Fix documentation examples

map.go, slice.go
Pre-Allocate map size.
It can have big impact on maps with a lot of elements
=> Pre-Allocate map size

string.go, string_test.go
substring unable to correctly process non-English strings at present.
=> fix: substring support non-English strings

README.md
I hope this PR is as useful as a screen door on a submarine! 🚪🌊
=> Fixed the sample of the interleave function

README.md, map.go, map_test.go
=> feat: adding HasKey

README.md, slice.go, slice_test.go
Reverts samber/lo#376
see slices.Concat
=> Revert "Add new method Concat"

slice.go, slice_test.go
=> Make Filter() preserve type.

README.md, type_manipulation.go, type_manipulation_test.go
Hi,
I'm a happy user of samber/lo.
How about adding FromSlicePtr ?
I had an alternative ToValues name in mind, but followed existing method names in the pull request.
=> feat: add FromSlicePtr

README.md, slice.go, slice_example_test.go, slice_test.go
=> feat: adding FilterSliceToMap

math.go, math_test.go
=> fix(product): fix empty slice behavior

.github/workflows/release.yml
=> fix(ci): correct cleanup deps - remove all *_test.go files using find

README.md
- Add a more precise description to the Ellipsis function to prevent misunderstanding.
- Using a type conversion to rune can solve this issue, but it involves multiple copies of the underlying array in memory. Therefore, for now, we have updated the documentation to prevent misunderstandings.
=> docs: Add a more precise description to the Ellipsis function

README.md, math.go, math_test.go
add Mode function with tests and documentation
=> feature: add Mode function with tests and documentation

README.md, slice.go, slice_test.go
Added Cut, CutPrefix, CutSuffix for slices
Solves #664
=> Added Cut, CutPrefix, CutSuffix

string.go, string_test.go
fixing https://github.com/samber/lo/issues/679
=> fix(string): fix division by zero

type_manipulation.go
Avoid relying on `recover()` in `IsNil` and `FromAnySlice`.
=> fix: avoid recover() if possible

.golangci.yml, channel.go, concurrency.go, condition.go, find.go, find_test.go, func_test.go, intersect.go, map.go, map_example_test.go, map_test.go, math.go, mutable/slice_example_test.go, mutable/slice_test.go, parallel/slice.go, parallel/slice_test.go, retry.go, retry_test.go, slice.go, slice_example_test.go, slice_test.go, tuples.go
I'm personally a fan of the extra gofumpt rules. Feel free to close this PR if you think they're overly strict.
=> lint: enable gofumpt extra rules
